name: PRIMARI
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- jupyter
- numpy
- pandas
- scipy
- statsmodels
- matplotlib
- seaborn
- plotly
- python-kaleido
- colorlover
- xlsxwriter
- xlrd